[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = ['Unite', 'UniteWithBufferDir']
hook_add = '''
source ~/.config/nvim/vimrc.d/plugins/lazy/unite.rc.vim
'''

[[plugins]]
repo = 'Shougo/vimfiler'
depends = 'unite.vim'
on_cmd = ['VimFilerTab', 'VimFiler', 'VimFilerExplorer']
hook_add = '''
source ~/.config/nvim/vimrc.d/plugins/lazy/vimfiler.rc.vim
'''

[[plugins]]
repo = 'osyo-manga/vim-over'
on_cmd = ['OverCommandLine']
hook_add = '''
nnoremap <Backspace> :OverCommandLine<CR>%s/
vnoremap <Backspace> "xy:OverCommandLine<CR>%s/<C-R>=escape(@x, '\\/.*$^~[]')<CR>//gc<Left><Left><Left>
'''

[[plugins]]
repo = 'simnalamburt/vim-mundo'
on_cmd = ['MundoToggle']
hook_add = '''
let g:loaded_python_provider = 1
let g:mundo_prefer_python3 = 1
'''
