[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['md']

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['md']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html']

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['jade', 'pug']

[[plugins]]
repo = 'wavded/vim-stylus'
on_ft = ['styl']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'lilydjwg/colorizer'
on_ft = ['css', 'scss', 'styl', 'vue']

[[plugins]]
repo = 'Shougo/context_filetype.vim'
on_ft = ['vue']

[[plugins]]
repo = 'osyo-manga/vim-precious'
on_ft = ['vue']

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = ['Unite', 'UniteWithBufferDir']
hook_add = '''
source ~/.config/nvim/vimrc.d/plugins/unite.rc.vim
'''

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
on_i = 1

[[plugins]]
repo = 'ujihisa/unite-colorscheme'
on_source = ['unite.vim']

[[plugins]]
repo = 'tacroe/unite-mark'
on_source = ['unite.vim']

[[plugins]]
repo = 'rhysd/unite-codic.vim'
on_source = ['unite.vim']

[[plugins]]
repo = 'h1mesuke/unite-outline'
on_source = ['unite.vim']

[[plugins]]
repo = 'pasela/unite-webcolorname'
on_source = ['unite.vim']

[[plugins]]
repo = 'Shougo/vimfiler'
depends = 'unite.vim'
on_cmd = ['VimFilerTab', 'VimFiler', 'VimFilerExplorer']
hook_add = '''
source ~/.config/nvim/vimrc.d/plugins/vimfiler.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'osyo-manga/vim-over'
on_cmd = ['OverCommandLine']
hook_add = '''
nnoremap <Backspace> :OverCommandLine<CR>%s/
vnoremap <Backspace> "xy:OverCommandLine<CR>%s/<C-R>=escape(@x, '\\/.*$^~[]')<CR>//gc<Left><Left><Left>
'''

[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1

[[plugins]]
repo = 'simnalamburt/vim-mundo'
on_cmd = ['MundoToggle']
hook_add = '''
let g:loaded_python_provider = 1
let g:mundo_prefer_python3 = 1
'''


[[plugins]]
repo = 'itchyny/thumbnail.vim'
on_cmd = ['Thumbnail']
