[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown']
hook_add = '''
noremap <Leader>bm :PrevimOpen<CR>
'''

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'jade', 'pug', 'vue']

[[plugins]]
repo = 'tmhedberg/matchit'
on_ft = ['html']

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee', 'vue']

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['jade', 'pug', 'vue']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'wavded/vim-stylus'
on_ft = ['stylus', 'vue']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'lilydjwg/colorizer'
on_ft = ['css', 'scss', 'stylus', 'vue']

[[plugins]]
repo = 'Shougo/context_filetype.vim'
on_ft = ['vue']

[[plugins]]
repo = 'osyo-manga/vim-precious'
on_ft = ['vue']

[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = ['Unite', 'UniteWithBufferDir']
hook_add = '''
source ~/.config/nvim/vimrc.d/plugins/unite.rc.vim
'''

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
on_i = 1

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo = 'ujihisa/unite-colorscheme'
on_source = ['unite.vim']

[[plugins]]
repo = 'tacroe/unite-mark'
on_source = ['unite.vim']

[[plugins]]
repo = 'rhysd/unite-codic.vim'
on_source = ['unite.vim']

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = ['unite.vim']

[[plugins]]
repo = 'pasela/unite-webcolorname'
on_source = ['unite.vim']

[[plugins]]
repo = 'Shougo/vimfiler'
depends = 'unite.vim'
on_cmd = ['VimFilerTab', 'VimFiler', 'VimFilerExplorer']
hook_add = '''
source ~/.config/nvim/vimrc.d/plugins/vimfiler.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'osyo-manga/vim-over'
on_cmd = ['OverCommandLine']
hook_add = '''
nnoremap <Backspace> :OverCommandLine<CR>%s/
vnoremap <Backspace> "xy:OverCommandLine<CR>%s/<C-R>=escape(@x, '\\/.*$^~[]')<CR>//gc<Left><Left><Left>
'''

[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1

[[plugins]]
repo = 'simnalamburt/vim-mundo'
on_cmd = ['MundoToggle']
hook_add = '''
let g:loaded_python_provider = 1
let g:mundo_prefer_python3 = 1
'''


[[plugins]]
repo = 'itchyny/thumbnail.vim'
on_cmd = ['Thumbnail']
