[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

#[[plugins]] # solarized
#repo = 'altercation/vim-colors-solarized'

[[plugins]] # solarized(qt)
repo = 'JulioJu/neovim-qt-colors-solarized-truecolor-only'

[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

#[[plugins]]
#repo = 't9md/vim-quickhl'
#
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'LeafCage/yankround.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'AndrewRadev/switch.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-replace'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-line'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'
